### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by gcampa** [danielpdev/angular-particle-effect-button#1]
Hi, following the instructions in the readme the project doesn't start:
Module not found: Error: Can't resolve '...\angular-particle-effect-button-master\dist\angular-particle-effect-button' in '..\angular-particle-effect-button-master\src\app'

any hint please?

**Comment by danielpdev** [comment]
Hi @gcampa ,
First, if you have problems when running locally https://github.com/danielpdev/angular-particle-effect-button you need to do the following steps:

You need to run `git clone https://github.com/danielpdev/angular-particle-effect-button.git`
`cd angular-particle-effect-button/ && npm install`
`ng build angular-particle-effect-button` -> now the dist folder should be available
`ng serve`

Second, if you just want to install and use the package:
Install: 
`npm i --save angular-particle-effect-button`
Import in your app and module:
`import { ParticleEffectButtonModule } from "angular-particle-effect-button";`
`@NgModule({
...
  imports: [ParticleEffectButtonModule]
...
})
`
Add it to HTML:
`<button libParticleEffectButton [pHidden]="hidden" (click)="hidden=!hidden">Hide me</button>`

Don't forget to install "animejs" as a dependency  -> https://www.npmjs.com/package/animejs
`npm i animejs`

Hope that helps and let me know if your issue has been fixed.

Thanks

**Comment by gcampa** [comment]
It works like a charme, thank you for your help, i was really looking forward on something with angular + animejs.

regards

**Comment by danielpdev** [comment]
@gcampa glad I help
happy coding!
