### ISSUE TITLE
peer dependency required (animejs@^2.2.0)

### ISSUE THREAD

**Issue by DoloMike** [danielpdev/angular-particle-effect-button#2]
`npm WARN angular-particle-effect-button@0.0.2 requires a peer of animejs@^2.2.0 but none is installed. You must install peer dependencies yourself.`

This statement shows during `npm i --save angular-particle-effect-button` if animejs is not already installed.

I propose either adding animejs@^2.2.0 to the package.json dependencies or updating the README to include `npm i --save animejs` as an installation step. I will submit a PR if either of these options would be accepted.

**Comment by danielpdev** [comment]
I've added animejs as a dependency 
`  "dependencies": {
    "animejs": "^2.2.0"
  }
`
